import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport:{width:1440,height:950}})
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text())})
await p.goto('http://localhost:4672/', { waitUntil:'networkidle' })
await p.waitForTimeout(600)
await p.evaluate(()=>{const el=[...document.querySelectorAll('#why h3')].find(e=>e.textContent.includes('Multi-Angle'));el&&el.scrollIntoView({block:'center'})})
await p.waitForTimeout(1000)
const front=()=>p.evaluate(()=>{const cs=[...document.querySelectorAll('.ds-dc-card')];let bz=-1,bt=null;cs.forEach(c=>{const z=parseInt(getComputedStyle(c).zIndex)||0;const t=c.querySelector('.ds-dc-title')?.textContent;if(z>bz){bz=z;bt=t}});return bt})
const click=(needle)=>p.evaluate((needle)=>{const c=[...document.querySelectorAll('.ds-dc-card')].find(x=>x.querySelector('.ds-dc-title')?.textContent.includes(needle));c.click()},needle)
const hover=(needle)=>p.evaluate((needle)=>{const c=[...document.querySelectorAll('.ds-dc-card')].find(x=>x.querySelector('.ds-dc-title')?.textContent.includes(needle));c.dispatchEvent(new MouseEvent('mouseover',{bubbles:true}))},needle)
const cursor=()=>p.evaluate(()=>getComputedStyle(document.querySelector('.ds-dc-card')).cursor)
console.log('start:', await front())
await click('40°'); await p.waitForTimeout(1000); console.log('click 40 ->', await front())
await click('75°'); await p.waitForTimeout(1000); console.log('click 75 ->', await front())
const before = await front()
await hover('90°'); await p.waitForTimeout(800); console.log('hover 90 (should NOT change):', await front(), '(was', before+')')
console.log('cursor:', await cursor())
console.log('errors:', errs.length?errs.slice(0,3):'none')
await b.close()
